[package]
name = "can-embedded"
version = "0.1.0"
authors = ["Pascal Hertleif <pascal@technocreatives.com>"]
edition = "2018"

[dependencies]
bitvec = { version = "0.22", default-features = false }
num-traits = "0.2.14"

[features]
debug = []
range_checked = []
